### ISSUE TITLE
not published to Pub

### ISSUE THREAD

**Issue by maks** [munificent/markymark#2]
Hi @munificent this looks really neat! but doesn't seem to have been published to Pub yet?

Also 1 liner PR for the Readme: `dart pub global activate markymark` now that standalone pub has been removed from the SDK.

**Comment by munificent** [comment]
Yeah, I basically just hacked this together for my own personal use. I have no intentions to actually support it or anything, so putting it on Pub felt like more trouble than I wanted to get myself into. You're certainly welcome to clone it and use it. :)
